# Site settings
title: Tyler Hughes
description: "A simple portfolio and blog"
url: "http://tylerhughes.info"
baseurl: ""
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: "randomlyknighted"

author:
  name: "Tyler Hughes"
  twitter_username: thughesIT
  github_username:  randomlyknighted
  linkedin_username:  thughes01

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
        layout: "post"

# Build settings
destination: _site
paginate: 10
permalink: /archive/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ["jekyll-paginate"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "screenshot.png"]
